services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: avito-db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
  ollama-init:
    image: ollama/ollama:latest
    restart: "no"
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
    entrypoint: ["/bin/sh", "-c"]
    command:
      - 'sleep 6 && ollama pull "qwen2.5:3b-instruct" && ollama pull "llava:7b"'
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
