export {
  aggregateCatalogReferenceCharacteristics,
  catalogReferenceChips,
  catalogReferenceFields,
  catalogReferenceTitleSuggestions,
  findCatalogReferenceBrand,
  findCatalogReferenceModel,
  firstCatalogReferenceVariant,
  normalizeReferenceSearchText,
  type CatalogReferenceAttributeInput,
  type CatalogReferenceBrand,
  type CatalogReferenceCharacteristic,
  type CatalogReferenceCreateSuggestion,
  type CatalogReferenceField,
  type CatalogReferenceItem,
  type CatalogReferenceModel,
  type CatalogReferenceSelectedModel,
  type CatalogReferenceTitleSuggestion,
  type CatalogReferenceVariant,
} from "../catalog-reference.service";
